title: Template of conference homepages
description: This is a template of conference homepages

google_analytics:
theme: jekyll-theme-cayman
owner_name: Zhigang Yao
owner_url: https://zhigang-yao.github.io/

last_updated: true
show_footer: true

## Local run:
markdown: kramdown
kramdown:
  input: GFM

## Github run:
# markdown: GFM